version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-focal
    
    parameters:
      browser:
        type: string
      test-file:
        type: string
    
    environment:
      TEST_ENV: ci
      CI: true
    
    steps:
      - checkout
      
      - node/install-packages:
          pkg-manager: npm
          
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps << parameters.browser >>
          
      - run:
          name: Run Playwright tests
          command: npx playwright test << parameters.test-file >> --project=<< parameters.browser >>
          
      - store_artifacts:
          path: playwright-report
          destination: playwright-report
          
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              browser: [chromium, firefox]
              test-file: ["tests/enhanced-e2e-journey.spec.js", "tests/e2e-user-journey.spec.js"]
          
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - test:
          matrix:
            parameters:
              browser: [chromium, firefox]
              test-file: ["tests/enhanced-e2e-journey.spec.js"]
